// <auto-generated />
namespace MVCUniversityCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v3addcreditstocourse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v3addcreditstocourse));
        
        string IMigrationMetadata.Id
        {
            get { return "202105242148491_v3 add credits to course"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
