// <auto-generated />
namespace MVCUniversityCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v2addfirstName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2addfirstName));
        
        string IMigrationMetadata.Id
        {
            get { return "202105242143559_v2 add firstName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
